.TH ZDICT 1 "2013-06-12"
.SH NAME
zdict \- Japanese to English dictionary
.SH SYNOPSIS
.B zdict
.RI [ options ]
.SH DESCRIPTION
.B zdict
is a simple lookup tool for English speakers learning Japanese.
Unlike other Japanese dictionaries, zdict uses romanji exclusively to
help ease the translation process.
.PP
.SH OPTIONS
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
